# Packing Name
WCP_SINGLE_BIN_NAME="box64"

# JSON Target
WCP_SINGLE_BIN_TARGET="\${bindir}/box64"

WCP_TYPE="Box64"
WCP_VERSION_CODE=0
#WCP_VERSION_CODE_DEFAULT=0
#WCP_VERSION_PREFIX=""
#WCP_VERSION_SUFFIX=""

WCP_DESC="Built on the Winlator WCP Hub (Upstream: ptitSeb)"
