# Packing DIR
WCP_DIR_64="system32"
WCP_DIR_32=""

# JSON Target
WCP_MOUNT_64="\${system32}"
#WCP_MOUNT_32="\${syswow64}"

WCP_TYPE="FEXCore"
WCP_VERSION_CODE=0
#WCP_VERSION_CODE_DEFAULT=0
#WCP_VERSION_PREFIX=""
#WCP_VERSION_SUFFIX=""

WCP_DESC="Built on the Winlator WCP Hub (Upstream: FEX-Emu)"
